version: '3'
services:
  api:
    build: .
    hostname: api
    restart: always
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
