# Generated by Django 4.0.3 on 2022-04-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswc', models.CharField(max_length=11, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('contributors', models.CharField(max_length=255)),
            ],
        ),
    ]
