# Generated by Django 4.0.3 on 2022-04-07 18:03

from django.db import migrations
from django.db.models import Q
from typing import Union
from ..models import MusicalWork as MusicalWorkClass
from ..utils import load_musical_works

APP_NAME = 'works_single_view'
MODEL_NAME = 'MusicalWork'


def find_existing_musical_work(musical_work: dict, MusicalWork: MusicalWorkClass) -> Union[MusicalWorkClass, None]:
    title = musical_work.get('title')
    iswc = musical_work.get('iswc')

    query = Q(title=title)
    if iswc:
        query.add(Q(iswc=iswc), Q.OR)

    db_musical_works: list[MusicalWork] = MusicalWorkClass.objects.filter(query)
    for db_musical_work in db_musical_works:
        if db_musical_work.is_another_version(musical_work):
            return db_musical_work

    return None


# Insert records from works_metadata.csv
def forwards_func(apps, schema_editor):
    MusicalWork: MusicalWorkClass = apps.get_model(APP_NAME, MODEL_NAME)
    musical_works_to_insert = load_musical_works()

    for musical_work_to_insert in musical_works_to_insert:
        existing_musical_work = find_existing_musical_work(musical_work_to_insert, MusicalWork)
        if existing_musical_work:
            existing_musical_work.merge(musical_work_to_insert)
            existing_musical_work.save()
        else:
            new_musical_work = MusicalWork(**musical_work_to_insert)
            new_musical_work.save()


# Rollback inserted records
def backwards_func(apps, schema_editor):
    MusicalWork: MusicalWorkClass = apps.get_model(APP_NAME, MODEL_NAME)
    MusicalWork.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('works_single_view', '0001_create_musical_work_model'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
